server:
 port: 443
 ssl:
  key-store: classpath:demo.lynnjy.cn.pfx
  key-store-password: 834n0o5e4ik
  key-store-type: PKCS12
spring:
 redis:
   database: 0
   host: 127.0.0.1
   port: 6379
   password:
   timeout: 10000
   pool:
     max-active: 8
     max-wait: -1
     min-idle: 0